# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tagdata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tagdata.proto',
  package='tagging',
  syntax='proto2',
  serialized_pb=_b('\n\rtagdata.proto\x12\x07tagging\"(\n\x08Sentence\x12\x0e\n\x06tokens\x18\x01 \x03(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\"A\n\tSentences\x12$\n\tsentences\x18\x01 \x03(\x0b\x32\x11.tagging.Sentence\x12\x0e\n\x06\x64omain\x18\x02 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENTENCE = _descriptor.Descriptor(
  name='Sentence',
  full_name='tagging.Sentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tokens', full_name='tagging.Sentence.tokens', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='tagging.Sentence.tags', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=66,
)


_SENTENCES = _descriptor.Descriptor(
  name='Sentences',
  full_name='tagging.Sentences',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentences', full_name='tagging.Sentences.sentences', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='domain', full_name='tagging.Sentences.domain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=133,
)

_SENTENCES.fields_by_name['sentences'].message_type = _SENTENCE
DESCRIPTOR.message_types_by_name['Sentence'] = _SENTENCE
DESCRIPTOR.message_types_by_name['Sentences'] = _SENTENCES

Sentence = _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), dict(
  DESCRIPTOR = _SENTENCE,
  __module__ = 'tagdata_pb2'
  # @@protoc_insertion_point(class_scope:tagging.Sentence)
  ))
_sym_db.RegisterMessage(Sentence)

Sentences = _reflection.GeneratedProtocolMessageType('Sentences', (_message.Message,), dict(
  DESCRIPTOR = _SENTENCES,
  __module__ = 'tagdata_pb2'
  # @@protoc_insertion_point(class_scope:tagging.Sentences)
  ))
_sym_db.RegisterMessage(Sentences)


# @@protoc_insertion_point(module_scope)
